Topkala4/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataLayer;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Dto.Other;
using Dto.Payment;
using Microsoft.AspNetCore.Identity;

using ZarinPal.Class;

namespace TopKala3.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private TopKala3Contex _ctx;
        private readonly IHttpContextAccessor _HttpContextAccessor;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly Payment _payment;

        public OrdersController(TopKala3Contex ctx, IHttpContextAccessor httpContextAccessor,
                                UserManager<ApplicationUser> userManager)
        {
            var expose = new Expose();
            _ctx = ctx;
            _HttpContextAccessor = httpContextAccessor;
            this.userManager = userManager;
            _payment = expose.CreatePayment();
        }


        
        public IActionResult AddToCart(ProductViewModel product)
        {
            var Reduction = product.Special;
            string CurrentUserID = _HttpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            Order order = _ctx.Orders.SingleOrDefault(o => o.UserId == CurrentUserID && !o.IsFinaly);
            if (order == null)
            {
                order = new Order()
                {
                    UserId = CurrentUserID,
                    CreateDate = DateTime.Now,
                    IsFinaly = false,
                    Sum = 0
                    
                };
                _ctx.Orders.Add(order);
                _ctx.SaveChanges();
                _ctx.OrderDetails.Add(new OrderDetail()
                {
                    OrderId = order.OrderId,
                    Count = 1,
                    Price =Reduction ? product.Price :product.PriceWithReduction,
                    ProductId = product.id,
                    Color = product.color

                });
                _ctx.SaveChanges();
            }
            else
            {
                var details = _ctx.OrderDetails.SingleOrDefault(d => d.OrderId == order.OrderId && d.ProductId == product.id);
                if (details == null)
                {
                    _ctx.OrderDetails.Add(new OrderDetail()
                    {
                        OrderId = order.OrderId,
                        Count = 1,
                        Price = Reduction ?  product.PriceWithReduction : product.Price ,
                        ProductId = product.id,
                        Color=product.color
                    });
                }
                else
                {
                    details.Count += 1;
                    _ctx.Update(details);
                }

                _ctx.SaveChanges();
            }
            UpdateSumOrder(order.OrderId);
            return RedirectToAction("ShowOrder");

        }




        public IActionResult ShowOrder()
        {
            string CurrentUserID = User.FindFirstValue(ClaimTypes.NameIdentifier);

            Order order = _ctx.Orders.SingleOrDefault(o => o.UserId == CurrentUserID && !o.IsFinaly);

            List<ShowOrderViewModel> _list = new List<ShowOrderViewModel>();
            if (order != null)
            {
                var details = _ctx.OrderDetails.Where(d => d.OrderId == order.OrderId).ToList();
                foreach (var item in details)
                {
                    var product = _ctx.Products.Include(a => a.productPathImages).FirstOrDefault(f => f.ProductId == item.ProductId);


                    _list.Add(new ShowOrderViewModel()
                    {
                        Count = item.Count,
                        ImageName = product.productPathImages.FirstOrDefault().ImagePath,
                        OrderDetailId = item.OrderDetailID,
                        Price = item.Price,
                        Sum = item.Count * item.Price,
                        Title = product.Name,
                        Color=item.Color
                    });

                }
            }

            return View(_list);
        }




        public IActionResult Delete(int id)
        {
            var orderDetail = _ctx.OrderDetails.Find(id);
            _ctx.Remove(orderDetail);
            _ctx.SaveChanges();
            return RedirectToAction("ShowOrder");
        }

        public IActionResult Command(int id, string command)
        {
            var orderDetail = _ctx.OrderDetails.Find(id);

            switch (command)
            {
                case "up":
                    {
                        orderDetail.Count += 1;
                        _ctx.Update(orderDetail);
                        break;
                    }
                case "down":
                    {
                        orderDetail.Count -= 1;
                        if (orderDetail.Count == 0)
                        {
                            _ctx.OrderDetails.Remove(orderDetail);
                        }
                        else
                        {
                            _ctx.Update(orderDetail);
                        }

                        break;
                    }
            }


            _ctx.SaveChanges();
            return RedirectToAction("ShowOrder");
        }





        public void UpdateSumOrder(int orderId)
        {
            var order = _ctx.Orders.Find(orderId);
            order.Sum = _ctx.OrderDetails.Where(o => o.OrderId == order.OrderId).Select(d => d.Count * d.Price).Sum();
            _ctx.Update(order);
            _ctx.SaveChanges();
        }


        public async Task<IActionResult> Payment()
        {
            string CurrentUserID = _HttpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var user = await userManager.FindByIdAsync(CurrentUserID);

            var order = _ctx.Orders.SingleOrDefault(o => !o.IsFinaly);
            if (order == null)
            {
                return NotFound();
            }

            var result = await _payment.Request(new DtoRequest()
            {
                Mobile = user.PhoneNumber,
                CallbackUrl = "http://topkalacore.ir/Home/OnlinePayment/" + order.OrderId,
                Description = "خرید",
                Email = user.Email,
                Amount = order.Sum,
                MerchantId = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            }, ZarinPal.Class.Payment.Mode.sandbox);

            var x = result.Status == 100;
            if (x)
            {
                return Redirect("https://sandbox.zarinpal.com/pg/StartPay/" + result.Authority);
            }
            else
            {
                return View("Shopping_Nobuy");
            }





            //var payment = new Payment(order.Sum);
            //var res =  payment.PaymentRequest($"پرداخت فاکتور شماره {order.OrderId}",
            //    "https://localhost:44313/Home/OnlinePayment/" + order.OrderId, user.Email, user.PhoneNumber);
            //var x = res.Result.Status == 100;
            //if (x)
            //{
            //    return Redirect("https://sandbox.zarinpal.com/pg/StartPay/" + res.Result.Authority);
            //}
            //else
            //{
            //    return View("Shopping_Nobuy");
            //}


        }
    }
}

Topkala4/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataLayer;
using Microsoft.EntityFrameworkCore;

namespace TopKala3.Controllers
{
    public class SearchController : Controller
    {
        private TopKala3Contex _db;
        public SearchController(TopKala3Contex _db)
        {
            this._db = _db;
        }


        [Route("/Search/{id}")]
        public async Task<IActionResult> SearchProduct(int id,string SortOrder,string Search,string SerachInProduct, int pageid=1)
        {

            int Count1 = 0;
            int skip = (pageid - 1) * 12;
           
            ViewBag.Id = id;
           var product = _db.Products.Include(c=>c.Category).Include(a=>a.productPathImages).Where(a => a.CategoryId == id).Select(g => new SearchViewModel()
            {
               ProductID =g.ProductId,
                ProductName =g.Name,
                 ProductPrice=g.Price,
                 ProductImage =g.productPathImages.FirstOrDefault().ImagePath,
                 Visit=g.Visit,
                 Date=g.CreatDateTime,       
                Categoryies = g.Category.Categories.ToList(),
                CategoryName=g.Category.Name,
               CategoryParentName = g.Category.Parent.Name,
               CategoryGrandParentName = g.Category.Parent.Parent.Name==null ? "Empty": g.Category.Parent.Parent.Name,
               special=g.IsSpecial,
               PriceReduction=g.PriceWithReduction,
               CategoryId=g.CategoryId

           });

       

            if (!String.IsNullOrEmpty(Search))
            {
                var pro =await  _db.Products.Include(a=>a.Category).Where(a=>a.Name.ToLower().Contains(Search)||a.Category.Name.ToLower().Contains(Search)).Select(g => new SearchViewModel()
                {
                    ProductID = g.ProductId,
                    ProductName = g.Name,
                    ProductPrice = g.Price,
                    ProductImage = g.productPathImages.FirstOrDefault().ImagePath,
                    Visit = g.Visit,
                    Date = g.CreatDateTime,
                    CategoryName = g.Category.Name,
                    CategoryParentName = g.Category.Parent.Name,
                    CategoryGrandParentName = g.Category.Parent.Parent.Name == null ? "Empty" : g.Category.Parent.Parent.Name,
                    special = g.IsSpecial,
                    PriceReduction = g.PriceWithReduction,
                    CategoryId = g.CategoryId

                }).ToListAsync();
                if(!pro.Any())
                {
                    return View("NonProduct");
                }

                else
                {
                    ViewBag.Name = pro.FirstOrDefault().CategoryName;
                    ViewBag.Count = pro.Count();
                    ViewBag.Idd = pro.FirstOrDefault().CategoryId;
                    return View(pro.OrderBy(a => a.ProductID).Skip(skip).Take(12));
                }
               
               
            }

            if (!String.IsNullOrEmpty(SerachInProduct))
            {
                var pro = product.Where(a => a.ProductName.ToLower().Contains(SerachInProduct));


                if (!pro.Any())
                {
                    return View("NonProduct");
                }

                else
                {
                    ViewBag.Name = pro.FirstOrDefault().CategoryName;
                    ViewBag.Count = pro.Count();
                    ViewBag.Idd = pro.FirstOrDefault().CategoryId;
                    return View(await pro.OrderBy(a => a.ProductID).Skip(skip).Take(12).ToListAsync());
                }
            }


                ViewBag.Count = product.Count();
            switch (SortOrder)
            {
                case "Normal":
                    
                    product = product.OrderBy(a => a.ProductID);
                    ViewBag.Name = product.FirstOrDefault().CategoryName;
                    ViewBag.Idd = product.FirstOrDefault().CategoryId;
                     Count1 = product.Count();
                    ViewBag.PageID = pageid;
                    ViewBag.PageCount = Count1 / 12;

                    return PartialView(await product.Skip(skip).Take(12).ToListAsync());
                    

                case "Visit":
                    
                    product = product.OrderByDescending(a => a.Visit);
                    ViewBag.Name = product.FirstOrDefault().CategoryName;
                    ViewBag.Idd = product.FirstOrDefault().CategoryId;
                     Count1 = product.Count();
                    ViewBag.PageID = pageid;
                    ViewBag.PageCount = Count1 / 12;
                    return PartialView(await product.Skip(skip).Take(12).ToListAsync());

                case "New":
                  
                    product = product.OrderByDescending(a => a.Date);
                    ViewBag.Name = product.FirstOrDefault().CategoryName;
                    ViewBag.Idd = product.FirstOrDefault().CategoryId;
                     Count1 = product.Count();
                    ViewBag.PageID = pageid;
                    ViewBag.PageCount = Count1 / 12;
                    return PartialView(await product.Skip(skip).Take(12).ToListAsync());

                case "Low":
                   
                    product = product.OrderBy(a => a.ProductPrice);
                    ViewBag.Name = product.FirstOrDefault().CategoryName;
                    ViewBag.Idd = product.FirstOrDefault().CategoryId;
                     Count1 = product.Count();
                    ViewBag.PageID = pageid;
                    ViewBag.PageCount = Count1 / 12;
                    return PartialView(await product.Skip(skip).Take(12).ToListAsync());

                case "High":
                    
                    product = product.OrderByDescending(a => a.ProductPrice);
                    ViewBag.Name = product.FirstOrDefault().CategoryName;
                    ViewBag.Idd = product.FirstOrDefault().CategoryId;
                     Count1 = product.Count();
                    ViewBag.PageID = pageid;
                    ViewBag.PageCount = Count1 / 12;
                    return PartialView(await product.Skip(skip).Take(12).ToListAsync());


            }

                                                                                                            
            ViewBag.Name = product.FirstOrDefault().CategoryName;
            ViewBag.Idd = product.FirstOrDefault().CategoryId;
            int Count = product.Count();
            ViewBag.PageID = pageid;
            ViewBag.PageCount = Count / 12;
            return View(await product.Skip(skip).Take(12).ToListAsync());
        }





        [Route("/Filter/{id}")]
        public async Task<IActionResult> Filter(int id, string SortOrder, string Search, string SerachInProduct, string CategoryName, int pageid = 1)
        {

            int Count1 = 0;
            int skip = (pageid - 1) * 12;

            ViewBag.Id = id;
            var product = _db.Products.Include(c => c.Category).Include(a => a.productPathImages).Where(a => a.CategoryId == id).Select(g => new SearchViewModel()
            {
                ProductID = g.ProductId,
                ProductName = g.Name,
                ProductPrice = g.Price,
                ProductImage = g.productPathImages.FirstOrDefault().ImagePath,
                Visit = g.Visit,
                Date = g.CreatDateTime,
                Categoryies = g.Category.Categories.ToList(),
                CategoryName = g.Category.Name,
                CategoryParentName = g.Category.Parent.Name,
                CategoryGrandParentName = g.Category.Parent.Parent.Name == null ? "Empty" : g.Category.Parent.Parent.Name,
                special = g.IsSpecial,
                PriceReduction = g.PriceWithReduction,
                CategoryId = g.CategoryId

            });



            if (!String.IsNullOrEmpty(Search))
            {
                var pro = await _db.Products.Include(a => a.Category).Where(a => a.Name.ToLower().Contains(Search) || a.Category.Name.ToLower().Contains(Search)).Select(g => new SearchViewModel()
                {
                    ProductID = g.ProductId,
                    ProductName = g.Name,
                    ProductPrice = g.Price,
                    ProductImage = g.productPathImages.FirstOrDefault().ImagePath,
                    Visit = g.Visit,
                    Date = g.CreatDateTime,
                    CategoryName = g.Category.Name,
                    CategoryParentName = g.Category.Parent.Name,
                    CategoryGrandParentName = g.Category.Parent.Parent.Name == null ? "Empty" : g.Category.Parent.Parent.Name,
                    special = g.IsSpecial,
                    PriceReduction = g.PriceWithReduction,
                    CategoryId = g.CategoryId

                }).ToListAsync();
                if (!pro.Any())
                {
                    return View("NonProduct");
                }

                else
                {
                    ViewBag.Name = pro.FirstOrDefault().CategoryName;
                    ViewBag.Count = pro.Count();
                    ViewBag.Idd = pro.FirstOrDefault().CategoryId;
                    return View(pro.OrderBy(a => a.ProductID).Skip(skip).Take(12));
                }


            }

            if (!String.IsNullOrEmpty(SerachInProduct))
            {
                var pro = product.Where(a => a.ProductName.ToLower().Contains(SerachInProduct));


                if (!pro.Any())
                {
                    return View("NonProduct");
                }

                else
                {
                    ViewBag.Name = pro.FirstOrDefault().CategoryName;
                    ViewBag.Count = pro.Count();
                    ViewBag.Idd = pro.FirstOrDefault().CategoryId;

Topkala4/Views/Shared/EmailView.cshtml
@model DataLayer.EmailLink

@{
    Layout = null;
}

<div style="direction: rtl; padding: 20px">
    <h2> دوست عزیز !</h2>
    <p>با تشکر از ثبت نام شما در سایت ما ، جهت فعال سازی حساب کاربری خود روی لینک زیر کلیک کنید .</p>
    <p>

        <a href="@Model.ConfirmLink">لینک فعالسازی</a>
    </p> 
    <hr />

</div>

Topkala4/Views/Shared/EmailViewPass.cshtml
@using Microsoft.Extensions.Configuration;
@model DataLayer.EmailLink

@inject IConfiguration configuration
@{
    Layout = null;

 
}

<div style="direction: rtl; padding: 20px">
    <h2> دوست عزیز !</h2>
    <p>دوست عزیز برای تغییر دادن رمز خود روی لینک زیر کلیک نمایید</p>
    <p>

        <a class="btn btn-danger" href="@Model.ConfirmLink">تغییر </a>
    </p>
    <hr />

</div>

Topkala4/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager

<!DOCTYPE html>
<html lang="fa">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="/img/apple-icon.png">
    <link rel="icon" type="image/png" href="assets/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
          name='viewport' />
    <title>Topkala</title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" href="/fonts/font-awesome/css/font-awesome.min.css" />
    <!-- CSS Files -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/css/now-ui-kit.css" rel="stylesheet" />
    <link href="/css/plugins/owl.carousel.css" rel="stylesheet" />
    <link href="/css/plugins/owl.theme.default.min.css" rel="stylesheet" />
    <link href="/css/main.css" rel="stylesheet" />
</head>

<body class="index-page sidebar-collapse">

    <!-- responsive-header -->
    <nav class="navbar direction-ltr fixed-top header-responsive">
        <div class="container">
            <div class="navbar-translate">
                <a class="navbar-brand" href="/">
                    <img src="/img/logo.png" height="24px" alt="">
                </a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                        data-target="#navigation" aria-controls="navigation-index" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
                <div class="search-nav default">
                    <form asp-area="" asp-action="SearchProduct" asp-controller="Search">
                        <input type="text" name="Search" placeholder="جستجو ...">
                        <button type="submit"><img src="/img/search.png" alt=""></button>
                    </form>
                    <ul>
                        @if (!signInManager.IsSignedIn(User))
                        {
                            <li><a asp-area="identity" asp-controller="Account" asp-action="Login"><i class="now-ui-icons users_single-02"></i></a></li>
                        }
                        else
                        {
                            <li><a asp-area="identity" asp-controller="Account" asp-action="Profile"><img src="/img/User.png" style="max-width:21px; margin-bottom:10px" /></a></li>

                        }


                        <li><a asp-area="" asp-action="ShowOrder" asp-controller="Orders"><i class="now-ui-icons shopping_basket"></i></a></li>
                    </ul>
                </div>
            </div>

            <div class="collapse navbar-collapse justify-content-end" id="navigation">
                <div class="logo-nav-res default text-center">
                    <a href="/">
                        <img src="/img/logo.png" height="36px" alt="">
                    </a>
                </div>

                @await Component.InvokeAsync("ResponsiveMenuViewComponent")

                @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                {

                    <a class="nav-link" asp-area="Admin" asp-action="IndexAdmin" asp-controller="Home">Admin</a>

                }

            </div>
        </div>
    </nav>
    <!-- responsive-header -->

    <div class="wrapper default">

        <!-- header -->
        <header class="main-header default">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2 col-md-3 col-sm-4 col-5">
                        <div class="logo-area default">
                            <a href="/">
                                <img src="/img/logo.png" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-5 col-sm-8 col-7">
                        <div class="search-area default">
                            <form asp-area="" asp-controller="Search" asp-action="SearchProduct" class="search">
                                <input class="S-input" type="text" name="Search" placeholder="نام کالا، برند و یا دسته مورد نظر خود را جستجو کنید…">
                                <button class="S-button" type="submit"><img src="/img/search.png" alt=""></button>
                            </form>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-12">



                        @if (signInManager.IsSignedIn(User))
                        {
                            <div class="user-login dropdown">
                                <a asp-area="identity" asp-controller="Account" asp-action="Profile" class="btn btn-neutral ">
                                    پنل کاربری <img src="/img/User.png" style="max-width:25px" />
                                </a>

                            </div>

                        }

                        else
                        {
                            <div class="user-login dropdown">
                                <a href="#" class="btn btn-neutral dropdown-toggle" data-toggle="dropdown"
                                   id="navbarDropdownMenuLink1">
                                    ورود / ثبت نام
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                                    <div class="dropdown-item">
                                        <a class="btn btn-info" asp-controller="Account" asp-action="Login">ورود به تاپ کالا</a>
                                    </div>
                                    <div class="dropdown-item font-weight-bold">
                                        <span>کاربر جدید هستید؟</span> <a class="register" asp-area="identity" asp-controller="Account" asp-action="Register">ثبت‌نام</a>
                                    </div>
                                </ul>
                            </div>
                        }


                        <div class="cart dropdown">
                            <a href="#" class="btn dropdown-toggle" data-toggle="dropdown" id="navbarDropdownMenuLink1">
                                <i class="now-ui-icons shopping_cart-simple"></i>
                                سبد خرید
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">


                                @await Component.InvokeAsync("CartComponent")
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
            <nav class="main-menu">
                <div class="container">

                    @await Component.InvokeAsync("MenuViewComponent")
                </div>

            </nav>
        </header>
        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
        {

            <a class="nav-link" asp-area="Admin" asp-action="IndexAdmin" asp-controller="Home">Admin</a>

        }
        <!-- header -->


        <main class="main default">
            <div class="container">
                @RenderBody()

            </div>
        </main>


        <footer class="main-footer default">
            <div class="back-to-top">
                <a href="#">
                    <span class="icon"><i class="now-ui-icons arrows-1_minimal-up"></i></span> <span>
                        بازگشت به
                        بالا
                    </span>
                </a>
            </div>
            <div class="container">

                <div class="info">
                    <div class="row">
                        <div class="col-12 col-lg-4">
                            <span>علیرضا مقدم</span>
                        </div>
                        <div class="col-12 col-lg-4">شماره تماس: 09906484438</div>
                        <div class="col-12 col-lg-4">آدرس ایمیل:<a href="#">alimoqdm420@gmail.com</a></div>

                    </div>
                </div>
            </div>

        </footer>
    </div>



    <!--   Core JS Files   -->
    <script src="/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
    <script src="/js/core/popper.min.js" type="text/javascript"></script>
    <script src="/js/core/bootstrap.min.js" type="text/javascript"></script>
    <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
    <script src="/js/plugins/bootstrap-switch.js"></script>
    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="/js/plugins/nouislider.min.js" type="text/javascript"></script>
    <!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
    <script src="/js/plugins/bootstrap-datepicker.js" type="text/javascript"></script>
    <!-- Share Library etc -->
    <script src="/js/plugins/jquery.sharrre.js" type="text/javascript"></script>
    <!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->
    <script src="/js/now-ui-kit.js" type="text/javascript"></script>
    <!--  CountDown -->
    <script src="/js/plugins/countdown.min.js" type="text/javascript"></script>
    <!--  Plugin for Sliders -->
    <script src="/js/plugins/owl.carousel.min.js" type="text/javascript"></script>
    <!--  Jquery easing -->
    <script src="/js/plugins/jquery.easing.1.3.min.js" type="text/javascript"></script>
    <!-- Main Js -->
    <script src="/js/main.js" type="text/javascript"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    

</body>


</html>