Topkala4/Areas/Admin/Controllers/CreateProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace TopKala3.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CreateProductController : Controller
    {
        private readonly TopKala3Contex _db;
        public CreateProductController(TopKala3Contex db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_db.Categories, "CategoryId", "Name");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,Name,Price,PriceWithReduction,Reduction,IsSpecial,Seller,Tags,Review,Visit,CountSell,CreatDateTime,CategoryId,BrandId,EnglishName")] Product product)
        {
            if (ModelState.IsValid)
            {
                 
                product.CreatDateTime = DateTime.Now;
                // محاسبه درصد تخفیف
                int Precent = product.Reduction;
                product.PriceWithReduction = (Precent * product.Price) / 100;
                product.PriceWithReduction = product.Price - product.PriceWithReduction;
                _db.Add(product);
                await _db.SaveChangesAsync();
                ViewBag.id = product.ProductId;
                return RedirectToAction("Next", new { id = product.ProductId });
            }
            ViewData["CategoryId"] = new SelectList(_db.Categories, "CategoryId", "Name", product.CategoryId);
           
            return View(product);
        }

        public IActionResult Next(int id)
        {

            var product = _db.Products.Include(a=>a.Brands).SingleOrDefault(p=>p.ProductId==id);
            ViewData["CategoryId"] = new SelectList(_db.Categories, "CategoryId", "Name", product.CategoryId);
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("ProductId,Name,Brand,Price,PriceWithReduction,Reduction,IsSpecial,Seller,Tags,Review,Visit,CountSell,CreatDateTime,CategoryId,BrandId,EnglishName")] Product product)
        {
            if (ModelState.IsValid)
            {
               
                    _db.Update(product);
                    await _db.SaveChangesAsync();
   
                return RedirectToAction("Next", new { id = product.ProductId }); 
            }
            ViewData["CategoryId"] = new SelectList(_db.Categories, "CategoryId", "Name", product.CategoryId);
            return View("Next",product);
        }


        public IActionResult PropertyDetail(int id)
        {
            ViewBag.productid = id;
            var query = _db.Properties.Include(p => p.product).Where(a=>a.ProductId==id);
      
            return View("PropertyDetail", query.ToList());
        }

        
        [HttpGet]
        public IActionResult Property(int id)
        {
            ViewBag.product = id;
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Property( [Bind("PropertiesId,ProductId,Title,Value")] Properties properties)
        {
            if (ModelState.IsValid)
            {
           
                _db.Add(properties);
                await _db.SaveChangesAsync();
                return RedirectToAction("PropertyDetail", new { id = properties.ProductId });
            }
            return View(properties);
        }


        [HttpGet]
        public JsonResult GetBrands(int CountryId)
        {
            var Brands = new SelectList(_db.Brands.Where(c => c.CategoryId == CountryId), "BrandId", "Value");
            return Json(Brands);

        }

        [HttpGet]
        public JsonResult BrandsEdit(int CountryId)
        {
            var Brands = new SelectList(_db.Brands.Where(c => c.CategoryId == CountryId), "BrandId", "Value");
            return Json(Brands);

        }










    }
}

Topkala4/Areas/Admin/Controllers/ProductColorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;

namespace TopKala2.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductColorsController : Controller
    {
        private readonly TopKala3Contex _context;

        public ProductColorsController(TopKala3Contex context)
        {
            _context = context;
        }
        public IActionResult ColorList(int id)
        {
            ViewBag.productid = id;
            var query = _context.ProductColors.Include(p => p.product).Where(a => a.ProductId == id);
            return View(query);
        }

        public IActionResult CreateColor(int id)
        {
            ViewBag.product = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateColor(IEnumerable<ProductColor> Model, int id)
        {

            foreach (var item in Model)
            {
                var Color = new ProductColor()
                {
                    ProductId = id,
                    ColorName = item.ColorName
                };
                _context.ProductColors.Add(Color);
            }

            _context.SaveChanges();
            return RedirectToAction("ColorList", new { id = id });

        }


        [HttpGet]
        public async Task<IActionResult> DeleteColor(int id)
        {
            // var objFromDb = _dbContext.Categories.Where(i=>i.CategoryId==id);
            var objFromDb = await _context.ProductColors.FindAsync(id);

            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting." });
            }

            _context.ProductColors.Remove(objFromDb);
            _context.SaveChanges();

            return Json(new { success = true, message = "Delete successful." });

        }


        public async Task<IActionResult> Edit(int? id, int ProductId)
        {

            ViewBag.ProductId = ProductId;

            if (id == null)
            {
                return NotFound();
            }

            var properties = await _context.ProductColors.FindAsync(id);
            if (properties == null)
            {
                return NotFound();
            }

            return View(properties);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductColorId,ProductId,ColorName")] ProductColor productColor, int ProductId)
        {
            if (id != productColor.ProductColorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productColor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductColorExists(productColor.ProductColorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ColorList", new { id = ProductId });
            }

            return View(productColor);
        }

        


        

        private bool ProductColorExists(int id)
        {
            return _context.ProductColors.Any(e => e.ProductColorId == id);
        }
    }
}

Topkala4/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using Microsoft.AspNetCore.Authorization;

namespace TopKala2.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly TopKala3Contex _context;

        public ProductsController(TopKala3Contex context)
        {
            _context = context;
        }

        // GET: Admin/Products
        public async Task<IActionResult> Index()
        {
            var topKalaContext2 = _context.Products.Include(p => p.Category).Include(p => p.Brands);
            return View(await topKalaContext2.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            var product = await _context.Products.FindAsync(id);

            if (product == null)
            {
                return Json(new { success = false, message = "Error while deleting." });
            }
            var color = await _context.ProductColors.Where(a => a.ProductId == product.ProductId).ToListAsync();
            foreach (var item in color)
            {
                _context.ProductColors.Remove(item);
            }
            var properties = await _context.Properties.Where(a => a.ProductId == product.ProductId).ToListAsync();
            foreach (var item in properties)
            {
                _context.Properties.Remove(item);
            }
            var image = await _context.ProductPathImages.Where(a => a.ProductId == product.ProductId).ToListAsync();
            foreach (var item in image)
            {
                _context.ProductPathImages.Remove(item);
            }
            var att = await _context.ProductAttributes.Where(a => a.ProductId == product.ProductId).ToListAsync();
            foreach (var item in att)
            {
                _context.ProductAttributes.Remove(item);
            }
            var com = await _context.Comments.Where(a => a.ProductId == product.ProductId).ToListAsync();
            foreach (var item in com)
            {
                _context.Comments.Remove(item);
            }
            var order = await _context.OrderDetails.Where(a => a.ProductId == product.ProductId).ToListAsync();
            foreach (var item in order)
            {
                _context.OrderDetails.Remove(item);
            }
            _context.SaveChanges();

            _context.Products.Remove(product);
           await _context.SaveChangesAsync();

            return Json(new { success = true, message = "Delete successful." });
        }

    }
}

Topkala4/Areas/Admin/Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using Microsoft.AspNetCore.Authorization;

namespace TopKala2.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class PropertiesController : Controller
    {
        private readonly TopKala3Contex _context;

        public PropertiesController(TopKala3Contex context)
        {
            _context = context;
        }

        public IActionResult PropList(int id)
        {
            ViewBag.productid = id;
            var query = _context.Properties.Include(p => p.product).Where(a => a.ProductId == id);
            return View(query);
        }

        public IActionResult CreateProp(int id)
        {
            ViewBag.product = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateProp(IEnumerable<Properties> Model,int id)
        {
                    
            foreach(var item in Model)
            {
                var Prop = new Properties()
                {
                    ProductId = id,
                    Title = item.Title,
                    Value = item.Value
                };
               _context.Properties.Add(Prop);
            }

            _context.SaveChanges();
            return RedirectToAction("PropList", new { id = id });

        }


        [HttpGet]
        public async Task<IActionResult> DeleteProp(int id)
        {
            // var objFromDb = _dbContext.Categories.Where(i=>i.CategoryId==id);
            var objFromDb = await _context.Properties.FindAsync(id);

            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting." });
            }

            _context.Properties.Remove(objFromDb);
            _context.SaveChanges();

            return Json(new { success = true, message = "Delete successful." });

        }



        public async Task<IActionResult> Edit(int? id,int ProductId)
        {

            ViewBag.ProductId = ProductId;

            if (id == null)
            {
                return NotFound();
            }

            var properties = await _context.Properties.FindAsync(id);
            if (properties == null)
            {
                return NotFound();
            }
          
            return View(properties);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PropertiesId,ProductId,Title,Value")] Properties properties,int ProductId)
        {
            if (id != properties.PropertiesId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(properties);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropertiesExists(properties.PropertiesId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("PropList", new { id = ProductId });
            }
     
            return View(properties);
        }




        private bool PropertiesExists(int id)
        {
            return _context.Properties.Any(e => e.PropertiesId == id);
        }
    }
}

Topkala4/Areas/Admin/Views/CreateProduct/Create.cshtml
@model DataLayer.Product

@{
    ViewData["Title"] = "Create";
}

<div class="card m-3 text-right fontiran">
    <form asp-action="Create">

        <div class="card-header">
            ایجاد محصول
        </div>
        <div class="card-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="CategoryId"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId" id="CategoryList">
                        <option>انتخاب </option>
                    </select>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-lg-2">
                    <label> برند </label>
                </div>
                <div class="col-12 col-lg-10">
                    <select asp-for="BrandId" class="form-control" id="BrandList">
                        <option> </option>
                    </select>

                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="EnglishName"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="EnglishName" class="form-control" />
                    <span asp-validation-for="EnglishName" class="text-danger"></span>
                </div>
            </div>
          
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="Reduction"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="Reduction" class="form-control" />
                    <span asp-validation-for="Reduction" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="IsSpecial"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="IsSpecial" type="checkbox" class="form-check-input" />
                    <span asp-validation-for="IsSpecial" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="Tags"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="Tags" class="form-control" />
                    <span asp-validation-for="Tags" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="Review"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <textarea asp-for="Review" class="form-control"></textarea>
                    <span asp-validation-for="Review" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="card-footer text-muted">
            <div class=" row">
                <div class="col-12">
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary btn-block" />
                    </div>
                </div>

            </div>
        </div>


    </form>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }

    <script src="~/ckeditor/ckeditor.js"></script>
    <script src="~/ckeditor/adapters/jquery.js"></script>
    <script>

        $(function () {
            $("#Review").ckeditor();
        })
    </script>


    <script type="text/javascript">
        //Insert default item "Select" in dropdownlist on load
        $(document).ready(function () {
            var items = "<option value='0'>انتخاب</option>";
            $("#BrandList").html(items);
        });

        //Bind City dropdownlist
        $("#CategoryList").change(function () {
            var CategoryId = $("#CategoryList").val();
            var url = "/Admin/CreateProduct/GetBrands";

            $.getJSON(url, { CountryId: CategoryId }, function (data) {
                var item = "<option >انتخاب</option>";
                $("#BrandList").empty();
                $.each(data, function (i, attr) {
                    item += '<option value="' + attr.value + '">' + attr.text + '</option>'
                });
                $("#BrandList").html(item);
            });
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Topkala4/Areas/Admin/Views/CreateProduct/Next.cshtml
@model DataLayer.Product
@{
    ViewData["Title"] = "Next";
}

<div class="card m-3 text-right fontiran ">
    <form asp-action="Edit">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" asp-for="Reduction" />
        <div class="card-header d-flex justify-content-between">
            <div>
                محصول
            </div>
            <div>
                <a asp-area="Admin" asp-controller="Products" asp-action="Index" class="btn btn-info">محصولات</a>
            </div>
        </div>
        <div class="card-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="CategoryId"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <select asp-for="CategoryId" class="form-control bg-light" asp-items="ViewBag.CategoryId"></select>
                    <span asp-validation-for="CategoryId" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-lg-2">
                    <label> برند </label>
                </div>
                @if (Model.BrandId != null)
                {
                    
            <div class="col-12 col-lg-10">
                <div class="d-flex " >
                    <button class="btn btn-info mx-1 ">  @Html.DisplayFor(modelItem => modelItem.Brands.Value) </button>

                    <select asp-for="BrandId" class="form-control" id="BrandList">
                        <option> </option>
                    </select>
                </div>
             

            </div>
                }
                else
                {
                    <div class="col-12 col-lg-10">
                        <select asp-for="BrandId" class="form-control" id="BrandList">
                            <option> </option>
                        </select>

                    </div>
                }

            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="Name" class="form-control bg-light" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="EnglishName"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="EnglishName" class="form-control bg-light" />
                    <span asp-validation-for="EnglishName" class="text-danger"></span>
                </div>
            </div>
           
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="Price"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="Price" class="form-control bg-light" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="Reduction"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="Reduction" class="form-control bg-light" />
                    <span asp-validation-for="Reduction" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="IsSpecial"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="IsSpecial" type="checkbox" class="form-check-input" />
                    <span asp-validation-for="IsSpecial" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-12 col-sm-2">
                    <label asp-for="Tags"></label>
                </div>
                <div class="col-12 col-sm-10">
                    <input asp-for="Tags" class="form-control bg-light" />
                    <span asp-validation-for="Tags" class="text-danger"></span>
                </div>
            </div>

        </div>
        <div class="card-footer text-muted">
            <div class="d-flex flex-column flex-sm-row justify-content-center justify-content-sm-start">
                
                    <div class="mx-1">
                        <div class="form-group">
                            <input type="submit" value="ویرایش" class="btn btn-danger btn-block" />
                        </div>
                    </div>
                    <div class="mx-1">
                        <div class="form-group">
                            <a asp-area="Admin" asp-action="PropList" asp-controller="Properties" asp-route-id="@Model.ProductId" class="btn text-black btn-block" style="background-color:#aae000">ویژگی ها </a>
                        </div>
                    </div>
                    <div class="mx-1">
                        <div class="form-group">
                            <a asp-area="Admin" asp-action="ColorList" asp-controller="ProductColors" asp-route-id="@Model.ProductId" class="btn text-white btn-block" style="background-color:#250188">رنگ ها </a>
                        </div>
                    </div>
                    <div class="mx-1">
                        <div class="form-group">
                            <a asp-area="Admin" asp-action="ImageList" asp-controller="ProductPathImages" asp-route-id="@Model.ProductId" class="btn  btn-block" style="background-color:#ff7840">عکس ها </a>
                        </div>
                    </div>
                    <div class="mx-1">
                        <div class="form-group">
                            <a asp-area="Admin" asp-action="Attribute" asp-controller="CreateProductAttribute" asp-route-id="@Model.ProductId" class="btn text-white  btn-block" style="background-color:#4531ba">مشخصات </a>
                        </div>
                    </div>
                </div>
            
  
        </div>


    </form>
</div>

@section Scripts{
    <script type="text/javascript">

        $(document).ready(function () {
            var CategoryId =  @Model.CategoryId;
            var url = "/Admin/CreateProduct/BrandsEdit";
            $.getJSON(url, { CountryId: CategoryId }, function (data) {
                var item = "";
                $("#BrandList").empty();
                $.each(data, function (i, attr) {
                    item += '<option value="' + attr.value + '">' + attr.text + '</option>'
                });
                $("#BrandList").html(item);
            });
        });







    </script>
} 