Topkala4/Areas/Admin/Controllers/CreateProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace TopKala3.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CreateProductController : Controller
    {
        private readonly TopKala3Contex _db;
        public CreateProductController(TopKala3Contex db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_db.Categories, "CategoryId", "Name");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,Name,Price,PriceWithReduction,Reduction,IsSpecial,Seller,Tags,Review,Visit,CountSell,CreatDateTime,CategoryId,BrandId,EnglishName")] Product product)
        {
            if (ModelState.IsValid)
            {
                 
                product.CreatDateTime = DateTime.Now;
                // محاسبه درصد تخفیف
                int Precent = product.Reduction;
                product.PriceWithReduction = (Precent * product.Price) / 100;
                product.PriceWithReduction = product.Price - product.PriceWithReduction;
                _db.Add(product);
                await _db.SaveChangesAsync();
                ViewBag.id = product.ProductId;
                return RedirectToAction("Next", new { id = product.ProductId });
            }
            ViewData["CategoryId"] = new SelectList(_db.Categories, "CategoryId", "Name", product.CategoryId);
           
            return View(product);
        }

        public IActionResult Next(int id)
        {

            var product = _db.Products.Include(a=>a.Brands).SingleOrDefault(p=>p.ProductId==id);
            ViewData["CategoryId"] = new SelectList(_db.Categories, "CategoryId", "Name", product.CategoryId);
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("ProductId,Name,Brand,Price,PriceWithReduction,Reduction,IsSpecial,Seller,Tags,Review,Visit,CountSell,CreatDateTime,CategoryId,BrandId,EnglishName")] Product product)
        {
            if (ModelState.IsValid)
            {
               
                    _db.Update(product);
                    await _db.SaveChangesAsync();
   
                return RedirectToAction("Next", new { id = product.ProductId }); 
            }
            ViewData["CategoryId"] = new SelectList(_db.Categories, "CategoryId", "Name", product.CategoryId);
            return View("Next",product);
        }


        public IActionResult PropertyDetail(int id)
        {
            ViewBag.productid = id;
            var query = _db.Properties.Include(p => p.product).Where(a=>a.ProductId==id);
      
            return View("PropertyDetail", query.ToList());
        }

        
        [HttpGet]
        public IActionResult Property(int id)
        {
            ViewBag.product = id;
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Property( [Bind("PropertiesId,ProductId,Title,Value")] Properties properties)
        {
            if (ModelState.IsValid)
            {
           
                _db.Add(properties);
                await _db.SaveChangesAsync();
                return RedirectToAction("PropertyDetail", new { id = properties.ProductId });
            }
            return View(properties);
        }


        [HttpGet]
        public JsonResult GetBrands(int CountryId)
        {
            var Brands = new SelectList(_db.Brands.Where(c => c.CategoryId == CountryId), "BrandId", "Value");
            return Json(Brands);

        }

        [HttpGet]
        public JsonResult BrandsEdit(int CountryId)
        {
            var Brands = new SelectList(_db.Brands.Where(c => c.CategoryId == CountryId), "BrandId", "Value");
            return Json(Brands);

        }










    }
}

Topkala4/Areas/Admin/Controllers/ProductPathImagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataLayer;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace TopKala2.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductPathImagesController : Controller
    {
        private readonly TopKala3Contex _context;
       
        private readonly IHostingEnvironment _environment;
        public ProductPathImagesController(TopKala3Contex context, IHostingEnvironment _environment)
        {
            _context = context;
            this._environment = _environment;
        }
        public IActionResult ImageList(int id)
        {
            ViewBag.productid = id;
            var query = _context.ProductPathImages.Include(p => p.product).Where(a => a.ProductId == id);
            return View(query);
        }


        [HttpGet]
        public IActionResult CreateImage(int id)
        {
            ViewBag.product = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
     
        public async Task<IActionResult> CreateImage(IEnumerable<DataLayer.ImageUpVm> Model, int id)
        {
            if (ModelState.IsValid)
            {
                var uploadsRootFolder = Path.Combine(_environment.WebRootPath, "ProductImages");
                if (!Directory.Exists(uploadsRootFolder))
                {
                    Directory.CreateDirectory(uploadsRootFolder);
                }
                foreach (var item in Model)
                {
                    if(item.Photo!=null)
                    {
                        Guid guid = Guid.NewGuid();
                        var filePath = Path.Combine(uploadsRootFolder, item.Photo.FileName);
                        var name = Path.GetFileName(filePath);
                        var Image = new ProductPathImage()
                        {
                            ImagePath = guid + Path.GetExtension(name),
                            ProductId = id

                        };

                        _context.ProductPathImages.Add(Image);
                        using (var fileStream = new FileStream(Path.Combine(uploadsRootFolder, Image.ImagePath), FileMode.Create))
                        {
                            await item.Photo.CopyToAsync(fileStream).ConfigureAwait(false);
                        }
                    }
                }
                _context.SaveChanges();

                return RedirectToAction("ImageList", new { id = id });
            }
            return View(Model);
        }



        [HttpGet]
        public async Task<IActionResult> DeleteImage(int id)
        {
            var objFromDb = await _context.ProductPathImages.FindAsync(id);

            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting." });
            }

            var uploadsRootFolder = Path.Combine(_environment.WebRootPath, "ProductImages");
            if (objFromDb.ImagePath != null)
            {
                System.IO.File.Delete(Path.Combine(uploadsRootFolder, objFromDb.ImagePath));
            }
            _context.ProductPathImages.Remove(objFromDb);
            _context.SaveChanges();

            return Json(new { success = true, message = "Delete successful." });
        }

        public async Task<IActionResult> Edit(int? id, int ProductId)
        {

            ViewBag.ProductId = ProductId;

            if (id == null)
            {
                return NotFound();
            }

            var properties = await _context.ProductPathImages.FindAsync(id);
            if (properties == null)
            {
                return NotFound();
            }

            return View(properties);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MyProperty,ProductId,ImagePath")] ProductPathImage productPathImage,IFormFile ImgsUp, int ProductId)
        {
            if (id != productPathImage.MyProperty)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (ImgsUp != null)
                {
                    var uploadsRootFolder = Path.Combine(_environment.WebRootPath, "ProductImages");
                    if (productPathImage.ImagePath != null)
                    {
                        System.IO.File.Delete(Path.Combine(uploadsRootFolder, productPathImage.ImagePath));
                    }



                    Guid guid = Guid.NewGuid();
                    var filePath = Path.Combine(uploadsRootFolder, ImgsUp.FileName);
                    var name = Path.GetFileName(filePath);
                    productPathImage.ImagePath = guid + Path.GetExtension(name);

                    using (var fileStream = new FileStream(Path.Combine(uploadsRootFolder, productPathImage.ImagePath), FileMode.Create))
                    {
                        await ImgsUp.CopyToAsync(fileStream).ConfigureAwait(false);
                    }

                }


                try
                {
                    _context.Update(productPathImage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductPathImageExists(productPathImage.MyProperty))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ImageList", new { id = ProductId });
            }

            return View(productPathImage);
        }


        private bool ProductPathImageExists(int id)
        {
            return _context.ProductPathImages.Any(e => e.MyProperty == id);
        }
    }
}

Topkala4/Areas/Admin/Views/ProductPathImages/CreateImage.cshtml
@{
    ViewData["Title"] = "CreateImage";
}
<div class="card m-3 text-right fontiran ">
    <form method="post" asp-action="CreateImage" asp-route-id="@ViewBag.product" enctype="multipart/form-data">

        <div class="card-header">
            ایجاد عکس
        </div>
        <div class="card-body card-frm ">

            <div class="form-group row card-subFrm ">
                <input name="Model[0].ProductId" type="hidden" value="@ViewBag.product" />
                <div class="col-12 col-lg-2">
                    <label>تصویر</label>
                </div>
                <div class="col-12 col-lg-10 mb-2">
                    <input type="file" name="Model[0].Photo" class="form-control border-Cus" />

                </div>

            </div>

        </div>
        <div class="m-2 text-muted">
            <div class="d-flex flex-column flex-sm-row justify-content-center justify-content-sm-start">
                <div class="mx-1">
                    <div class="form-group">
                        <input type="submit" value="ایجاد" class="btn btn-primary btn-block" />
                    </div>
                </div>
                <div class="mx-1">
                    <div class="form-group">
                        <a id="AddMore" class="btn btn-success text-white btn-block">اضافه کردن </a>
                    </div>
                </div>
                <div class="mx-1 RmvInput">
                    <div class="form-group">
                        <a id="RemoveElmnt" class="btn btn-danger text-white btn-block">حذف کردن </a>
                    </div>
                </div>
                <div class="mx-1">
                    <div class="form-group">
                        <a asp-action="ImageList" asp-route-id="@ViewBag.product" class="btn btn-block text-white" style="background-color:#4531ba">برگشت </a>
                    </div>
                </div>
            </div>
        </div>


    </form>
</div>



<div hidden id="AddForm">

    <div class="form-group mt-3 row card-subFrm ">
        <input name="Model[0].ProductId" type="hidden" value="@ViewBag.product" />
        <div class="col-12 col-lg-2">
            <label>تصویر</label>
        </div>
        <div class="col-12 col-lg-10 mb-2">
            <input type="file" name="Model[#].Photo" class="form-control border-Cus" />

        </div>


    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>

        var count = 1;
         $(".RmvInput").hide();
        $("#AddMore").click(function (e) {
            e.preventDefault();

            var formContent = $("#AddForm");
            var Content = formContent.html().replace(/#/g, count);


            $(".card-frm").append(Content);
            count++;


        if (count >= 2) {
            $(".RmvInput").show(500);
        }
        else {
              $(".RmvInput").hide();
        }
        });

         $("#RemoveElmnt").click(function (e) {
             e.preventDefault();
             $('.card-frm').children('.card-subFrm').last().remove();

             count--;


        if (count >= 2) {
            $(".RmvInput").show(500);
        }
        else {
              $(".RmvInput").hide();
        }
        });


    </script>



}

<style>
    .border-Cus {
        border: 0px solid #8F8F8F;
    }
</style>

Topkala4/Areas/Admin/Views/ProductPathImages/Edit.cshtml
@model DataLayer.ProductPathImage

@{
    ViewData["Title"] = "Edit";
}

    <div class="card m-3 text-right fontiran ">
        <form asp-action="Edit" asp-route-ProductId="@ViewBag.ProductId"enctype="multipart/form-data">

            <div class="card-header">
                ویرایش عکس ها
            </div>
            <div class="card-body">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ProductId" value="@ViewBag.ProductId" />
                <input type="hidden" asp-for="MyProperty" />
                <div class="form-group row">
                    <div class="col-12 col-lg-1">
                        <label asp-for="ImagePath"></label>
                    </div>
                    <div class="col-12 col-lg-5" style="max-width:300px;">
                        <img src="~/ProductImages/@Model.ImagePath" class="img-thumbnail img-fluid"    />
                    </div>
                    <div class="col-12 col-lg-3">
                        <input type="file" name="ImgsUp"  class="form-control border-Cus" />
                        <span asp-validation-for="ImagePath" class="text-danger"></span>
                    </div>
                </div>


            </div>
            <div class="card-footer text-muted">
                <div class=" row">
                    <div class="col-6">
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary btn-block" />
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <a asp-action="ImageList" asp-route-id="@ViewBag.ProductId" class="btn btn-success btn-block">Back </a>
                        </div>
                    </div>
                </div>
            </div>


        </form>
    </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    .border-Cus {
        border: 0px solid #8F8F8F;
    }
</style>

Topkala4/Areas/Admin/Views/ProductPathImages/ImageList.cshtml
@model IEnumerable<DataLayer.ProductPathImage>


@{
    ViewData["Title"] = "ImageList";
}




    <div class="row m-4 px-1 py-4 border backgroundWhite" dir="ltr">
        <div class="col-lg-12 mb-4">
            <div class=" text-right">
                <a asp-action="CreateImage" asp-route-id="@ViewBag.productid" class="btn btn-primary fontiran"><i class="fas fa-plus"></i> &nbsp; ایجاد تصویر</a>
                <a asp-controller="CreateProduct" asp-action="Next" asp-route-id="@ViewBag.productid" class="btn btn-info m-1 fontiran"> &nbsp; محصول</a>
            </div>
        </div>

        <div class="col-lg-12 col-12" >
            @if (Model != null)
            {


                <table id="myTable" class="table table-striped  table-bordered fontiran dt-responsive nowrap" width="100%" dir="rtl">
                    <thead>
                        <tr>
                            <th class="d-flex flex-wrap">
                                <div style="white-space: nowrap;display: inline-block;
  width: 230px;
  overflow: hidden;
  text-overflow: ellipsis;">
                                    @Html.DisplayNameFor(model => model.product.Name)
                                </div>

                            </th>

                            <th>
                                @Html.DisplayNameFor(model => model.ImagePath)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td class="d-flex flex-wrap">
                                <div style="white-space: nowrap;display: inline-block;
  width: 230px;
  overflow: hidden;
  text-overflow: ellipsis;">
                                    @Html.DisplayFor(modelItem => item.product.Name)
                                </div>

                            </td>
                            <td>
                                <img src="~/ProductImages/@item.ImagePath" class="img-thumbnail" style="max-width:120px;" asp-append-version="true" />
                            </td>

                            <td>
                                <a class="btn " asp-action="Edit" asp-route-id="@item.MyProperty" asp-route-ProductId="@ViewBag.productid" style="background-color:#ff7840"><i class='far fa-edit'></i> </a>

                                <a class="btn text-white" onclick="Delete(@item.MyProperty)" style="background-color:#4531ba">    <i class='far fa-trash-alt'></i> </a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            }

        </div>
    </div>






@section Scripts{
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });

        function Delete(id) {
            swal({

                title: "Are you sure you want to delete",

                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes",
                closeOnconfirm: true,

            }, function () {
                $.ajax({
                    type: 'GET',
                    url: "/Admin/ProductPathImages/DeleteImage/" + id,
                    dataType: 'json',
                    success: function (data) {
                        if (data.success) {
                            toastr.success(data.message);
                            setTimeout(function () { location.reload(); },100 );



                        }
                        else {
                            toastr.error(data.message);
                        }
                    },
                    error: function (error) {
                        toastr.error("U cant delet this ");

                    }

                });
            });
        }



    </script>

}